version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - gradle bootJar
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/demo-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes